.TH PULSEAUDIO-MIXER-APPLET 1

.SH NAME

pulseaudio-mixer-applet - a per-application volume control panel applet for GNOME

.SH SYNOPSIS

.B pulseaudio-mixer-applet

.SH DESCRIPTION

Pulseaudio Mixer Applet is a small applet for the GNOME panel that can control both input and output device volumes, and individual playback stream volumes. It also provides a convenient way to change the default input and output devices, and move application audio streams to different devices. 

To use this applet, right click on the GNOME panel, select "Add to Panel...", and select "PulseAudio Mixer Applet" from the list.
